name: test
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl -k  https://selflearning-vercel-deploy-test.vercel.app/addNumber

