name: Call API-addNumber

on:
#   schedule:
#     - cron: '0 */6 * * *'
#     - cron: '0 0 * * *'
#     - cron: '0 4 * * *'
#     - cron: '0 8 * * *'

  # 允許你從 Action 頁簽上手動執行 workflow
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        # run: echo Hello, world!
        run: curl -k  https://red-test-yongsin0129.vercel.app/addData

